export { default as Home } from './home'
export { default as Navbar } from './Navbar'
export { default as Footer } from './Footer'
export { default as About } from './about'
export { default as AuthBox } from './auth'
export { default as Restaurants } from './restaurants'
export { default as OneRestaurant } from './OneRestaurant'
export { default as AuthGit } from './auth_github'
